"""renaming column

Revision ID: 641322641386
Revises: faaa92a6d4ce
Create Date: 2023-11-11 11:04:00.521982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641322641386'
down_revision = 'faaa92a6d4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
